name: prueba_tecnica_flutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  equatable: ^2.0.7


  path_provider: ^2.1.5
  path: ^1.8.3
  sqflite: ^2.3.1

  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^6.0.0

  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter_icons:
  android: true        
  ios: true
  image_path: "assets/icon/iconapp.png"

  # Recomendado para Android adaptive icon:
  adaptive_icon_background: "#000000"     # fondo s√≥lido
  adaptive_icon_foreground: "assets/icon/iconapp.png"

  min_sdk_android: 21
  remove_alpha_ios: true



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/

  