name: prueba_tecnica_flutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  equatable: ^2.0.7


  path_provider: ^2.1.5
  path: ^1.8.3
  sqflite: ^2.3.1

  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  